/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bw1XRvvtRawYwtZXSCfw3q
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariants_0XnN8G2ShfVa } from "./PlasmicGlobalVariant__Mobile"; // plasmic-import: 0XnN8G2shfVa/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  mobile: useScreenVariants_0XnN8G2ShfVa
});
