/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bw1XRvvtRawYwtZXSCfw3q
// Component: oyUjyWZqENHC
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bw1XRvvtRawYwtZXSCfw3q/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bw1XRvvtRawYwtZXSCfw3q/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: bw1XRvvtRawYwtZXSCfw3q/projectcss
import sty from "./PlasmicHeroCarousel.module.css"; // plasmic-import: oyUjyWZqENHC/css
import Vector682Icon from "./icons/PlasmicIcon__Vector682"; // plasmic-import: kslu_maehgy2/icon
import ChevronLeft2Icon from "./icons/PlasmicIcon__ChevronLeft2"; // plasmic-import: L2w2_AvDwX-I/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: z90cpJ33GqFp/icon
import ChevronRight2Icon from "./icons/PlasmicIcon__ChevronRight2"; // plasmic-import: AOKmv43I-Izn/icon

createPlasmicElementProxy;

export const PlasmicHeroCarousel__VariantProps = new Array();

export const PlasmicHeroCarousel__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHeroCarousel__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"heroCarousel"}
      data-plasmic-override={overrides.heroCarousel}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.heroCarousel
      )}
    >
      <div
        data-plasmic-name={"frame10847"}
        data-plasmic-override={overrides.frame10847}
        className={classNames(projectcss.all, sty.frame10847)}
      >
        <div
          data-plasmic-name={"landingHeroCard"}
          data-plasmic-override={overrides.landingHeroCard}
          className={classNames(projectcss.all, sty.landingHeroCard)}
        >
          <div
            data-plasmic-name={"_1207971410455451254850947787928748998899864N4"}
            data-plasmic-override={
              overrides._1207971410455451254850947787928748998899864N4
            }
            className={classNames(
              projectcss.all,
              sty._1207971410455451254850947787928748998899864N4
            )}
          />
        </div>
      </div>
      <div
        data-plasmic-name={"info"}
        data-plasmic-override={overrides.info}
        className={classNames(projectcss.all, sty.info)}
      >
        <div
          data-plasmic-name={"info2"}
          data-plasmic-override={overrides.info2}
          className={classNames(projectcss.all, sty.info2)}
        >
          <div
            data-plasmic-name={"title"}
            data-plasmic-override={overrides.title}
            className={classNames(projectcss.all, sty.title)}
          >
            <div
              data-plasmic-name={"frame63296"}
              data-plasmic-override={overrides.frame63296}
              className={classNames(projectcss.all, sty.frame63296)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ucFkO
                )}
              >
                {"Thomas And Friends\nThe britt allcroft collection"}
              </div>
              <div
                data-plasmic-name={"frame10852"}
                data-plasmic-override={overrides.frame10852}
                className={classNames(projectcss.all, sty.frame10852)}
              >
                <Vector682Icon
                  className={classNames(projectcss.all, sty.svg__illQg)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"statusLabel"}
                  data-plasmic-override={overrides.statusLabel}
                  className={classNames(projectcss.all, sty.statusLabel)}
                >
                  <div
                    data-plasmic-name={"title2"}
                    data-plasmic-override={overrides.title2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.title2
                    )}
                  >
                    {"online only"}
                  </div>
                </div>
                <Vector682Icon
                  className={classNames(projectcss.all, sty.svg__m4GGg)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eevLy
                  )}
                >
                  {"aug 13 - sept 9, 2025"}
                </div>
                <Vector682Icon
                  className={classNames(projectcss.all, sty.svg__h8NBn)}
                  role={"img"}
                />
              </div>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__v9D9Y
              )}
            >
              {
                "A chance to own true and tangible pieces from some of the most beloved TV series ever broadcast"
              }
            </div>
            <div
              data-plasmic-name={"gigaButton"}
              data-plasmic-override={overrides.gigaButton}
              className={classNames(projectcss.all, sty.gigaButton)}
            >
              <div
                data-plasmic-name={"text11"}
                data-plasmic-override={overrides.text11}
                className={classNames(projectcss.all, sty.text11)}
              >
                <div
                  data-plasmic-name={"button29"}
                  data-plasmic-override={overrides.button29}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.button29
                  )}
                >
                  {"View Auction"}
                </div>
                {false ? (
                  <div
                    data-plasmic-name={"button30"}
                    data-plasmic-override={overrides.button30}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button30
                    )}
                  >
                    {"View Auction"}
                  </div>
                ) : null}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        data-plasmic-name={"button31"}
        data-plasmic-override={overrides.button31}
        className={classNames(projectcss.all, sty.button31)}
      >
        <ChevronLeft2Icon
          className={classNames(projectcss.all, sty.svg__aQoU)}
          role={"img"}
        />

        {false ? (
          <div
            data-plasmic-name={"text12"}
            data-plasmic-override={overrides.text12}
            className={classNames(projectcss.all, sty.text12)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__uMcU8
              )}
            >
              {"Button"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__z9Hmb
              )}
            >
              {"Button"}
            </div>
          </div>
        ) : null}
        {false ? (
          <ChevronDownIcon
            className={classNames(projectcss.all, sty.svg___9VzwR)}
            role={"img"}
          />
        ) : null}
      </div>
      <div
        data-plasmic-name={"button32"}
        data-plasmic-override={overrides.button32}
        className={classNames(projectcss.all, sty.button32)}
      >
        <ChevronRight2Icon
          className={classNames(projectcss.all, sty.svg__vF5Es)}
          role={"img"}
        />

        {false ? (
          <div
            data-plasmic-name={"text13"}
            data-plasmic-override={overrides.text13}
            className={classNames(projectcss.all, sty.text13)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2YEk7
              )}
            >
              {"Button"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fZ0Lt
              )}
            >
              {"Button"}
            </div>
          </div>
        ) : null}
        {false ? (
          <ChevronDownIcon
            className={classNames(projectcss.all, sty.svg___34Nad)}
            role={"img"}
          />
        ) : null}
      </div>
      {false ? (
        <div
          data-plasmic-name={"carouselIndicator"}
          data-plasmic-override={overrides.carouselIndicator}
          className={classNames(projectcss.all, sty.carouselIndicator)}
        >
          <div
            data-plasmic-name={"component1"}
            data-plasmic-override={overrides.component1}
            className={classNames(projectcss.all, sty.component1)}
          >
            <div
              data-plasmic-name={"group13"}
              data-plasmic-override={overrides.group13}
              className={classNames(projectcss.all, sty.group13)}
            >
              <div
                data-plasmic-name={"rectangle41"}
                data-plasmic-override={overrides.rectangle41}
                className={classNames(projectcss.all, sty.rectangle41)}
              />

              <div
                data-plasmic-name={"rectangle42"}
                data-plasmic-override={overrides.rectangle42}
                className={classNames(projectcss.all, sty.rectangle42)}
              />
            </div>
          </div>
          <div
            data-plasmic-name={"frame10915"}
            data-plasmic-override={overrides.frame10915}
            className={classNames(projectcss.all, sty.frame10915)}
          >
            <div
              data-plasmic-name={"dot"}
              data-plasmic-override={overrides.dot}
              className={classNames(projectcss.all, sty.dot)}
            >
              <div
                data-plasmic-name={"rectangle262"}
                data-plasmic-override={overrides.rectangle262}
                className={classNames(projectcss.all, sty.rectangle262)}
              />
            </div>
            <div
              data-plasmic-name={"dot2"}
              data-plasmic-override={overrides.dot2}
              className={classNames(projectcss.all, sty.dot2)}
            >
              <div
                data-plasmic-name={"rectangle263"}
                data-plasmic-override={overrides.rectangle263}
                className={classNames(projectcss.all, sty.rectangle263)}
              />
            </div>
            <div
              data-plasmic-name={"dot3"}
              data-plasmic-override={overrides.dot3}
              className={classNames(projectcss.all, sty.dot3)}
            >
              <div
                data-plasmic-name={"rectangle264"}
                data-plasmic-override={overrides.rectangle264}
                className={classNames(projectcss.all, sty.rectangle264)}
              />

              <div
                data-plasmic-name={"rectangle265"}
                data-plasmic-override={overrides.rectangle265}
                className={classNames(projectcss.all, sty.rectangle265)}
              />
            </div>
            <div
              data-plasmic-name={"dot4"}
              data-plasmic-override={overrides.dot4}
              className={classNames(projectcss.all, sty.dot4)}
            >
              <div
                data-plasmic-name={"rectangle266"}
                data-plasmic-override={overrides.rectangle266}
                className={classNames(projectcss.all, sty.rectangle266)}
              />
            </div>
            <div
              data-plasmic-name={"dot5"}
              data-plasmic-override={overrides.dot5}
              className={classNames(projectcss.all, sty.dot5)}
            >
              <div
                data-plasmic-name={"rectangle267"}
                data-plasmic-override={overrides.rectangle267}
                className={classNames(projectcss.all, sty.rectangle267)}
              />
            </div>
            <div
              data-plasmic-name={"dot6"}
              data-plasmic-override={overrides.dot6}
              className={classNames(projectcss.all, sty.dot6)}
            >
              <div
                data-plasmic-name={"rectangle268"}
                data-plasmic-override={overrides.rectangle268}
                className={classNames(projectcss.all, sty.rectangle268)}
              />
            </div>
            {false ? (
              <div
                data-plasmic-name={"dot7"}
                data-plasmic-override={overrides.dot7}
                className={classNames(projectcss.all, sty.dot7)}
              >
                <div
                  data-plasmic-name={"rectangle269"}
                  data-plasmic-override={overrides.rectangle269}
                  className={classNames(projectcss.all, sty.rectangle269)}
                />
              </div>
            ) : null}
            {false ? (
              <div
                data-plasmic-name={"dot8"}
                data-plasmic-override={overrides.dot8}
                className={classNames(projectcss.all, sty.dot8)}
              >
                <div
                  data-plasmic-name={"rectangle270"}
                  data-plasmic-override={overrides.rectangle270}
                  className={classNames(projectcss.all, sty.rectangle270)}
                />
              </div>
            ) : null}
          </div>
        </div>
      ) : null}
    </div>
  );
}

const PlasmicDescendants = {
  heroCarousel: [
    "heroCarousel",
    "frame10847",
    "landingHeroCard",
    "_1207971410455451254850947787928748998899864N4",
    "info",
    "info2",
    "title",
    "frame63296",
    "frame10852",
    "statusLabel",
    "title2",
    "gigaButton",
    "text11",
    "button29",
    "button30",
    "button31",
    "text12",
    "button32",
    "text13",
    "carouselIndicator",
    "component1",
    "group13",
    "rectangle41",
    "rectangle42",
    "frame10915",
    "dot",
    "rectangle262",
    "dot2",
    "rectangle263",
    "dot3",
    "rectangle264",
    "rectangle265",
    "dot4",
    "rectangle266",
    "dot5",
    "rectangle267",
    "dot6",
    "rectangle268",
    "dot7",
    "rectangle269",
    "dot8",
    "rectangle270"
  ],

  frame10847: [
    "frame10847",
    "landingHeroCard",
    "_1207971410455451254850947787928748998899864N4"
  ],

  landingHeroCard: [
    "landingHeroCard",
    "_1207971410455451254850947787928748998899864N4"
  ],

  _1207971410455451254850947787928748998899864N4: [
    "_1207971410455451254850947787928748998899864N4"
  ],

  info: [
    "info",
    "info2",
    "title",
    "frame63296",
    "frame10852",
    "statusLabel",
    "title2",
    "gigaButton",
    "text11",
    "button29",
    "button30"
  ],

  info2: [
    "info2",
    "title",
    "frame63296",
    "frame10852",
    "statusLabel",
    "title2",
    "gigaButton",
    "text11",
    "button29",
    "button30"
  ],

  title: [
    "title",
    "frame63296",
    "frame10852",
    "statusLabel",
    "title2",
    "gigaButton",
    "text11",
    "button29",
    "button30"
  ],

  frame63296: ["frame63296", "frame10852", "statusLabel", "title2"],
  frame10852: ["frame10852", "statusLabel", "title2"],
  statusLabel: ["statusLabel", "title2"],
  title2: ["title2"],
  gigaButton: ["gigaButton", "text11", "button29", "button30"],
  text11: ["text11", "button29", "button30"],
  button29: ["button29"],
  button30: ["button30"],
  button31: ["button31", "text12"],
  text12: ["text12"],
  button32: ["button32", "text13"],
  text13: ["text13"],
  carouselIndicator: [
    "carouselIndicator",
    "component1",
    "group13",
    "rectangle41",
    "rectangle42",
    "frame10915",
    "dot",
    "rectangle262",
    "dot2",
    "rectangle263",
    "dot3",
    "rectangle264",
    "rectangle265",
    "dot4",
    "rectangle266",
    "dot5",
    "rectangle267",
    "dot6",
    "rectangle268",
    "dot7",
    "rectangle269",
    "dot8",
    "rectangle270"
  ],

  component1: ["component1", "group13", "rectangle41", "rectangle42"],
  group13: ["group13", "rectangle41", "rectangle42"],
  rectangle41: ["rectangle41"],
  rectangle42: ["rectangle42"],
  frame10915: [
    "frame10915",
    "dot",
    "rectangle262",
    "dot2",
    "rectangle263",
    "dot3",
    "rectangle264",
    "rectangle265",
    "dot4",
    "rectangle266",
    "dot5",
    "rectangle267",
    "dot6",
    "rectangle268",
    "dot7",
    "rectangle269",
    "dot8",
    "rectangle270"
  ],

  dot: ["dot", "rectangle262"],
  rectangle262: ["rectangle262"],
  dot2: ["dot2", "rectangle263"],
  rectangle263: ["rectangle263"],
  dot3: ["dot3", "rectangle264", "rectangle265"],
  rectangle264: ["rectangle264"],
  rectangle265: ["rectangle265"],
  dot4: ["dot4", "rectangle266"],
  rectangle266: ["rectangle266"],
  dot5: ["dot5", "rectangle267"],
  rectangle267: ["rectangle267"],
  dot6: ["dot6", "rectangle268"],
  rectangle268: ["rectangle268"],
  dot7: ["dot7", "rectangle269"],
  rectangle269: ["rectangle269"],
  dot8: ["dot8", "rectangle270"],
  rectangle270: ["rectangle270"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeroCarousel__ArgProps,
          internalVariantPropNames: PlasmicHeroCarousel__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeroCarousel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "heroCarousel") {
    func.displayName = "PlasmicHeroCarousel";
  } else {
    func.displayName = `PlasmicHeroCarousel.${nodeName}`;
  }
  return func;
}

export const PlasmicHeroCarousel = Object.assign(
  // Top-level PlasmicHeroCarousel renders the root element
  makeNodeComponent("heroCarousel"),
  {
    // Helper components rendering sub-elements
    frame10847: makeNodeComponent("frame10847"),
    landingHeroCard: makeNodeComponent("landingHeroCard"),
    _1207971410455451254850947787928748998899864N4: makeNodeComponent(
      "_1207971410455451254850947787928748998899864N4"
    ),
    info: makeNodeComponent("info"),
    info2: makeNodeComponent("info2"),
    title: makeNodeComponent("title"),
    frame63296: makeNodeComponent("frame63296"),
    frame10852: makeNodeComponent("frame10852"),
    statusLabel: makeNodeComponent("statusLabel"),
    title2: makeNodeComponent("title2"),
    gigaButton: makeNodeComponent("gigaButton"),
    text11: makeNodeComponent("text11"),
    button29: makeNodeComponent("button29"),
    button30: makeNodeComponent("button30"),
    button31: makeNodeComponent("button31"),
    text12: makeNodeComponent("text12"),
    button32: makeNodeComponent("button32"),
    text13: makeNodeComponent("text13"),
    carouselIndicator: makeNodeComponent("carouselIndicator"),
    component1: makeNodeComponent("component1"),
    group13: makeNodeComponent("group13"),
    rectangle41: makeNodeComponent("rectangle41"),
    rectangle42: makeNodeComponent("rectangle42"),
    frame10915: makeNodeComponent("frame10915"),
    dot: makeNodeComponent("dot"),
    rectangle262: makeNodeComponent("rectangle262"),
    dot2: makeNodeComponent("dot2"),
    rectangle263: makeNodeComponent("rectangle263"),
    dot3: makeNodeComponent("dot3"),
    rectangle264: makeNodeComponent("rectangle264"),
    rectangle265: makeNodeComponent("rectangle265"),
    dot4: makeNodeComponent("dot4"),
    rectangle266: makeNodeComponent("rectangle266"),
    dot5: makeNodeComponent("dot5"),
    rectangle267: makeNodeComponent("rectangle267"),
    dot6: makeNodeComponent("dot6"),
    rectangle268: makeNodeComponent("rectangle268"),
    dot7: makeNodeComponent("dot7"),
    rectangle269: makeNodeComponent("rectangle269"),
    dot8: makeNodeComponent("dot8"),
    rectangle270: makeNodeComponent("rectangle270"),
    // Metadata about props expected for PlasmicHeroCarousel
    internalVariantProps: PlasmicHeroCarousel__VariantProps,
    internalArgProps: PlasmicHeroCarousel__ArgProps
  }
);

export default PlasmicHeroCarousel;
/* prettier-ignore-end */
