/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: bw1XRvvtRawYwtZXSCfw3q
// Component: r-IsABN_mh32
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: bw1XRvvtRawYwtZXSCfw3q/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: bw1XRvvtRawYwtZXSCfw3q/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: bw1XRvvtRawYwtZXSCfw3q/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: r-IsABN_mh32/css
import Vector6Icon from "./icons/PlasmicIcon__Vector6"; // plasmic-import: 9BQo6wVO6Ekn/icon
import FacebookIcon from "./icons/PlasmicIcon__Facebook"; // plasmic-import: fMcysc8BHIqM/icon
import TwitterIcon from "./icons/PlasmicIcon__Twitter"; // plasmic-import: qDPIBl4sjxC2/icon
import UnionIcon from "./icons/PlasmicIcon__Union"; // plasmic-import: 2e7xcWwaupSZ/icon
import BrandsYoutubeIcon from "./icons/PlasmicIcon__BrandsYoutube"; // plasmic-import: 9o0bvT4F0b2I/icon

createPlasmicElementProxy;

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFooter__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"footer"}
      data-plasmic-override={overrides.footer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.footer
      )}
    >
      <div
        data-plasmic-name={"frame226"}
        data-plasmic-override={overrides.frame226}
        className={classNames(projectcss.all, sty.frame226)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__fPgK1
          )}
        >
          {"JULIEN*S \nTHE AUCTION HOUSE \nTO THE STARS"}
        </div>
        <div
          data-plasmic-name={"frame10331"}
          data-plasmic-override={overrides.frame10331}
          className={classNames(projectcss.all, sty.frame10331)}
        >
          <div
            data-plasmic-name={"frame221"}
            data-plasmic-override={overrides.frame221}
            className={classNames(projectcss.all, sty.frame221)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bru5X
              )}
            >
              {"AUCTIONS"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2TFtg
              )}
            >
              {"Sell"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1Ozyo
              )}
            >
              {"Discover"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lpLVl
              )}
            >
              {"ABOUT"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kT7Ex
              )}
            >
              {"CATALOGs"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__qZesK)}>
            <Vector6Icon
              className={classNames(projectcss.all, sty.svg__dB8MA)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"frame12"}
            data-plasmic-override={overrides.frame12}
            className={classNames(projectcss.all, sty.frame12)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__sWoD0
              )}
            >
              {"Press"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__g1VVk
              )}
            >
              {"Partnerships"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dzuZw
              )}
            >
              {"Privacy"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__k9A1A
              )}
            >
              {"Terms & Conditions"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nU868
              )}
            >
              {"Terms of use"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bIl2I
              )}
            >
              {"Contact Us"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__i7Lon)}>
            <Vector6Icon
              className={classNames(projectcss.all, sty.svg__xMlso)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"socialIcons"}
            data-plasmic-override={overrides.socialIcons}
            className={classNames(projectcss.all, sty.socialIcons)}
          >
            <FacebookIcon
              className={classNames(projectcss.all, sty.svg___6Np2Q)}
              role={"img"}
            />

            <TwitterIcon
              className={classNames(projectcss.all, sty.svg__nmcEi)}
              role={"img"}
            />

            <UnionIcon
              className={classNames(projectcss.all, sty.svg__ll4R4)}
              role={"img"}
            />

            <BrandsYoutubeIcon
              className={classNames(projectcss.all, sty.svg__p0XnF)}
              role={"img"}
            />
          </div>
        </div>
      </div>
      <div
        data-plasmic-name={"frame225"}
        data-plasmic-override={overrides.frame225}
        className={classNames(projectcss.all, sty.frame225)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___0Zoew
          )}
        >
          {
            "Julien's Auctions | 13007 S. Western Avenue, Gardena, California 90249\nPhone: 310-836-1818 | Fax: 310-742-0155"
          }
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__zN5Xr
          )}
        >
          {"\u00a9 2003-2023 Julien's Auctions"}
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  footer: [
    "footer",
    "frame226",
    "frame10331",
    "frame221",
    "frame12",
    "socialIcons",
    "frame225"
  ],

  frame226: ["frame226", "frame10331", "frame221", "frame12", "socialIcons"],
  frame10331: ["frame10331", "frame221", "frame12", "socialIcons"],
  frame221: ["frame221"],
  frame12: ["frame12"],
  socialIcons: ["socialIcons"],
  frame225: ["frame225"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFooter__ArgProps,
          internalVariantPropNames: PlasmicFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "footer") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("footer"),
  {
    // Helper components rendering sub-elements
    frame226: makeNodeComponent("frame226"),
    frame10331: makeNodeComponent("frame10331"),
    frame221: makeNodeComponent("frame221"),
    frame12: makeNodeComponent("frame12"),
    socialIcons: makeNodeComponent("socialIcons"),
    frame225: makeNodeComponent("frame225"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
